<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2010 Magento Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<!-- This is my file -->
<?php
$_option = $this->getOption();
?>
<dt class="zp-attachment"><label><?php echo  $this->htmlEscape($_option->getTitle()) ?><?php if ($_option->getIsRequire()): ?><span class="required">&nbsp;*</span><?php endif; ?></label>
    <?php echo $this->getFormatedPrice() ?></dt>
<dd<?php if ($_option->decoratedIsLast){?> class="last"<?php }?>>
<script type="text/javascript">
if(undefined == window.AjaxUpload){
  var au = document.createElement('script'); au.type = 'text/javascript';
  au.src = '<?php echo $this->helper("attachments/upload")->getUploadJsUrl("js/ajaxupload.js")?>';
  (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(au);
}
</script>
<?php echo $this->helper('attachments/upload')->uploadControl($_option);?>
<?php if ($_option->getFileExtension()): ?>
<p class="no-margin"><?php echo Mage::helper('catalog')->__('Allowed file extensions to upload')?>: <strong><?php echo $_option->getFileExtension() ?></strong></p>
<?php endif; ?>
<?php if ($_option->getImageSizeX() > 0): ?>
<p class="no-margin"><?php echo Mage::helper('catalog')->__('Maximum image width')?>: <strong><?php echo $_option->getImageSizeX() ?> <?php echo Mage::helper('catalog')->__('px.')?></strong></p>
<?php endif; ?>
<?php if ($_option->getImageSizeY() > 0): ?>
<p class="no-margin"><?php echo Mage::helper('catalog')->__('Maximum image height')?>: <strong><?php echo $_option->getImageSizeY() ?> <?php echo Mage::helper('catalog')->__('px.')?></strong></p>
<?php endif; ?>
</dd>
