<?php
/**
 * Created by JetBrains PhpStorm.
 * User: pp
 * Date: 3/16/11
 * Time: 8:26 PM
 * To change this template use File | Settings | File Templates.
 */
 ?>
<script type="text/javascript">

OptionTemplateDistromap = '<table class="border" cellpadding="0" cellspacing="0">'+
        '<tr class="headings">'+
            '<th class="type-price"><?php echo Mage::helper('catalog')->__('Price') ?></th>'+
            '<th class="type-type"><?php echo Mage::helper('catalog')->__('Price Type') ?></th>'+
            '<th class="type-sku"><?php echo Mage::helper('catalog')->__('SKU') ?></th>'+
        '</tr>'+
        '<tr>'+
            '<td><input class="input-text type="text" name="product[options][{{option_id}}][price]" value="{{price}}"></td>'+
            '<td><?php echo $this->getPriceTypeSelectHtml() ?></td>'+
            '<td><input type="text" class="input-text" name="product[options][{{option_id}}][sku]" value="{{sku}}"></td>'+
        '</tr>'+
    '</table>';

if ($('option_panel_type_map')) {
    $('option_panel_type_map').remove();
}

</script>
