<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>

<head>
<?php echo $this->getChildHtml('head') ?>
</head>

<body>
  <?php $design = Mage::getDesign(); ?>

  <script type="text/javascript">
    var skinUrl="<?php echo $design->getSkinUrl('images/image-edit/'); ?>";
  </script>

  <?php if (!isset($_GET['fit_in_field'])): ?>
    <div id="imageEditorLeft">
      <ul>
          <li id="imageEditorRotateRight" title="<?php echo $this->__('Rotate Image Right'); ?>">
            <img src="<?php echo $design->getSkinUrl('images/image-edit/rotate_r.png'); ?>" alt="" />
            <span><?php echo $this->__('Rotate right'); ?></span>
          </li>
          <li id="imageEditorRotateLeft" title="<?php echo $this->__('Rotate Image Left'); ?>">
            <img src="<?php echo $design->getSkinUrl('images/image-edit/rotate_l.png'); ?>" alt="" />
            <span><?php echo $this->__('Rotate left'); ?></span>
          </li>
          <li id="imageEditorCrop" title="<?php echo $this->__('Crop Image'); ?>">
            <img src="<?php echo $design->getSkinUrl('images/image-edit/crop.png'); ?>" alt="" />
            <span><?php echo $this->__('Crop'); ?></span>
          </li>
          <li id="imageEditorRestore" title="<?php echo $this->__('Undo all changes'); ?>">
            <img src="<?php echo $design->getSkinUrl('images/image-edit/restore.png'); ?>" alt="" />
            <span><?php echo $this->__('Restore'); ?></span>
          </li>
          <li id="imageEditorDelete" title="<?php echo $this->__('Delete Image'); ?>">
            <img src="<?php echo $design->getSkinUrl('images/image-edit/delete.png'); ?>" alt="" />
            <span><?php echo $this->__('Delete'); ?></span>
          </li>
      </ul>
    </div>
  <?php endif; ?>

        <div style="position:absolute;right:5px;bottom:90px;">
          <img src="" id="imageEditorPreview" alt="Image" style="display:none" />
        </div>

        <div style="position:absolute;right:5px;bottom:5px;min-width:600px;">
          <table id="imageEditorInfo">
            <tr>
              <td id="imageEditorInfoBar"></td>
              <td id="imageEditorInfoTooltip"></td>
            </tr>
          </table>

          <form id="imageEditorCropForm">
            <input type="hidden" name="zetaprints-CropX1" id="imageEditorCropX" />
            <input type="hidden" name="zetaprints-CropY1" id="imageEditorCropY" />
            <input type="hidden" name="zetaprints-CropX2" id="imageEditorCropX2" />
            <input type="hidden" name="zetaprints-CropY2" id="imageEditorCropY2" />
            <input type="hidden" name="Cropw" id="imageEditorCropW" />
            <input type="hidden" name="Croph" id="imageEditorCropH" />
            <a href="javascript:void(0)" id="imageEditorApplyCrop">
              <img border="0" src="<?php echo $design->getSkinUrl('images/image-edit/save.png'); ?>" alt="Save" />
            </a>
          </form>
        </div>


</body>
</html>
