<script type="text/javascript">
//<![CDATA[
jQuery(document).ready(function($) {
  $('#preview-image-page-1').css('display', 'block');
  $('#input-fields-page-1').css('display', 'block');
  $('#stock-images-page-1').css('display', 'block');
  $('#color-pickers-page-1').css('display', 'block');

  $('div.image-tabs li:first').addClass('selected');

  previews = [];
  template_id = '<?php echo $this->getProduct()->getSku(); ?>';
  number_of_pages = $('div.zetaprints-template-preview').length;

  $('<input type="hidden" name="zetaprints-TemplateID" value="' + template_id +'" />').appendTo('#product_addtocart_form');

  $('div.image-tabs li').click(function () {
    $('div.image-tabs li').removeClass('selected');

    $('div.zetaprints-template-preview:visible, div.zetaprints-page-input-fields:visible, div.zetaprints-page-stock-images:visible, zetaprints-page-color-pickers:visible').css('display', 'none');

    $(this).addClass('selected');
    var page = $('img', this).attr('rel');

    $('#preview-image-' + page + ', #input-fields-' + page + ', #stock-images-' + page + ', #color-pickers-' + page).css('display', 'block');
  });

  function save_order_request () {
    var update_preview_button = $('input.update-preview').unbind('click').addClass('disable');
    $('div.save-order img.ajax-loader').css('display', 'inline');

    $.ajax({
      url: '<?php echo $this->getUrl('web-to-print/order'); ?>',
      type: 'POST',
      data: 'id=<?php echo $this->getProduct()->getId(); ?>&zetaprints-TemplateID=' + template_id + '&zetaprints-Previews=' + previews.join(','),
      dataType: 'text',
      error: function (XMLHttpRequest, textStatus, errorThrown) {
        $(update_preview_button).bind('click', update_preview).removeClass('disable');
        $('div.save-order img.ajax-loader').css('display', 'none');
        alert('Can\'t save order'); },
      success: function (data, textStatus) {
        if (parseInt(data) > 0) {
          //parent.document.location = '<?php echo $this->getUrl('checkout/cart/add'); ?>?qty=1&product=' + data;
          var url_array = $('#product_addtocart_form').attr('action').split('/');
          url_array[url_array.length - 2] = data;
          $('#product_addtocart_form').attr('action', url_array.join('/'));
          productAddToCartForm.submit();
        } else {
          //parent.document.location = '<?php echo $this->getUrl('checkout/cart'); ?>';
        } }
    } );
  };

  $('div.add-to-holder button.form-button').attr('onclick', null).click(save_order_request);

  function update_preview () {
    $('div.update-preview span').css('display', 'inline');
    $('img.ajax-loader').css('display', 'inline');

    var update_preview_button = $('input.update-preview').unbind('click').hide();
    var page = '' + $('div.image-tabs li.selected img').attr('rel');

    if (page == "undefined")
      page = 'page-1';

    $.ajax({
      url: '<?php echo $this->getUrl('web-to-print/preview'); ?>',
      type: 'POST',
      data: $('#product_addtocart_form').serialize() + '&zetaprints-From=' + page.split('-')[1],
      error: function (XMLHttpRequest, textStatus, errorThrown) {
        $('div.update-preview span').css('display', 'none');
        $('img.ajax-loader').css('display', 'none');
        $(update_preview_button).bind('click', update_preview).show();
        alert('Can\'t get preview image: ' + textStatus); },
      success: function (data, textStatus) {
        $('#preview-image-' + page + ' a').attr('href', data);
        $('#preview-image-' + page + ' img').attr('src', data);

        var image_name = data.split('/preview/')[1]
        previews[parseInt(page.split('-')[1]) - 1] = image_name;

        var thumb_url = data.split('/preview/')[0] + '/thumb/' + image_name.split('.')[0] + '_100x100.' + image_name.split('.')[1];
        $('div.image-tabs img[rel=' + page + ']').attr('src', thumb_url);

        if (previews.length == number_of_pages) {
          $('div.save-order input').removeClass('disable');
          $('div.save-order span').css('display', 'none');
          $('div.save-order input').bind('click', save_order_request);
        }

        $('div.update-preview span').css('display', 'none');
        $('img.ajax-loader').css('display', 'none');
        $(update_preview_button).bind('click', update_preview).show(); }
    });
  }

  $('input.update-preview').click(update_preview);

  $('div.zetaprints-page-color-pickers ul.colors-selector li').each(function () {
    var color_sample = $('div.color-sample', this);
    var color_input = $('input.color', this);

    $(color_sample).ColorPicker({
      color: '#804080',
      onBeforeShow: function (colpkr) {
        $(colpkr).draggable();
        return false;
      },
      onShow: function (colpkr) {
        $(colpkr).fadeIn(500);
        return false;
      },
      onHide: function (colpkr) {
        $(colpkr).fadeOut(500);
        return false;
      },
      onSubmit: function (hsb, hex, rgb, el) {
        $(color_sample).css('backgroundColor', '#' + hex);
        $(color_input).val('#' + hex).attr('checked', true).change();
        $(el).ColorPickerHide();
      }
    });
  });

  $('div.zetaprints-template-preview a').fancybox({
    'zoomOpacity': true,
    'overlayShow': false,
    'centerOnScroll': false,
    'zoomSpeedChange': 200,
    'zoomSpeedIn': 500,
    'zoomSpeedOut' : 500,
    'callbackOnShow': function () { $('img#fancy_img').attr('title', 'Click to close'); } });

  $('div.zetaprints-page-input-fields input[title], div.zetaprints-page-input-fields textarea[title]').qtip({
    position: { corner: { target: 'bottomLeft' } },
        show: { delay: 1, solo: true, when: { event: 'focus' } },
        hide: { when: { event: 'unfocus' } }
  });

  $('div.zetaprints-page-stock-images select[title]').qtip({
    position: { corner: { target: 'topLeft' }, adjust: { y: -30 } },
        show: { delay: 1, solo: true, when: { event: 'focus' } },
        hide: { when: { event: 'unfocus' } }
  });

  $('div.zetaprints-page-stock-images select.stock-images-selector').msDropDown();

  $('div.zetaprints-page-color-pickers ul.colors-selector').vchecks();
});
//]]>
</script>
