<?php
/**
 * OrderApproval
 *
 * @category design
 * @package base_default
 */
?>

<div class="col2-set">
  <div class="col-1">
    <div class="box">
      <div class="box-title">
        <h3><?php echo $this->__('Contact Information') ?></h3>
      </div>

      <div class="box-content">
        <p>
          <?php echo $this->htmlEscape($this->getCustomer()->getName()) ?>
          <br />
          <?php echo $this->htmlEscape($this->getCustomer()->getEmail()) ?>
        </p>
      </div>
    </div>
  </div>
</div>
