<meta http-equiv="Content-Type" content="<?php echo $this->getContentType() ?>" />

<script type="text/javascript">
//<![CDATA[
  var imageEditorUpdateURL = '<?php echo Mage::helper('webtoprint')
    ->_getUrl('web-to-print/image/update'); ?>';
  var imageEditorId = '<?php echo $this->getRequest()->getParam('id') ?>';
  var imageEditorZpURL = '<?php echo Mage::getStoreConfig('zpapi/settings/w2p_url'); ?>';
  var imageEditorDelimeter = '&';
  var imageEditorQueryAppend = '';
//]]>
</script>

<script type="text/javascript" src="<?php echo Mage::getUrl('web-to-print/Trans'); ?>"></script>
<?php echo $this->getCssJsHtml() ?>
