<!DOCTYPE html
     PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xml:lang="<?php echo $this->getLang(); ?>"
      lang="<?php echo $this->getLang(); ?>">

<head>
<?php echo $this->getChildHtml('head') ?>
</head>

<body>
  <?php $design = Mage::getDesign(); ?>

  <script type="text/javascript">
    var skinUrl="<?php echo $design->getSkinUrl('images/image-edit/'); ?>";
  </script>

    <div id="imageEditorLeftSidebar">
      <ul>
          <li id="imageEditorCropFit" title="<?php echo $this->__('Fit image in field'); ?>">
            <img src="<?php echo $design->getSkinUrl('images/image-edit/fit-to-field-crop-icon.png'); ?>" alt="" />
            <span><?php echo $this->__('Fit in field'); ?></span>
          </li>
          <li id="imageEditorRotateRight" title="<?php echo $this->__('Rotate Image Right'); ?>">
            <img src="<?php echo $design->getSkinUrl('images/image-edit/rotate_r.png'); ?>" alt="" />
            <span><?php echo $this->__('Rotate right'); ?></span>
          </li>
          <li id="imageEditorRotateLeft" title="<?php echo $this->__('Rotate Image Left'); ?>">
            <img src="<?php echo $design->getSkinUrl('images/image-edit/rotate_l.png'); ?>" alt="" />
            <span><?php echo $this->__('Rotate left'); ?></span>
          </li>
          <li id="imageEditorCrop" title="<?php echo $this->__('Crop Image'); ?>">
            <img src="<?php echo $design->getSkinUrl('images/image-edit/crop.png'); ?>" alt="" />
            <span><?php echo $this->__('Crop'); ?></span>
          </li>
          <li id="imageEditorRestore" title="<?php echo $this->__('Undo all changes'); ?>">
            <img src="<?php echo $design->getSkinUrl('images/image-edit/restore.png'); ?>" alt="" />
            <span><?php echo $this->__('Restore'); ?></span>
          </li>
          <li id="imageEditorDelete" title="<?php echo $this->__('Delete Image'); ?>">
            <img src="<?php echo $design->getSkinUrl('images/image-edit/delete.png'); ?>" alt="" />
            <span><?php echo $this->__('Delete'); ?></span>
          </li>
      </ul>
    </div>

  <div id="userImagePreviewContainer">
    <img src="" id="userImagePreview" />
  </div>

  <div id="imageEditorBottomPanel">

    <form id="imageEditorCropForm">
      <input type="hidden" name="zetaprints-CropX1" id="imageEditorCropX" />
      <input type="hidden" name="zetaprints-CropY1" id="imageEditorCropY" />
      <input type="hidden" name="zetaprints-CropX2" id="imageEditorCropX2" />
      <input type="hidden" name="zetaprints-CropY2" id="imageEditorCropY2" />
      <input type="hidden" name="Cropw" id="imageEditorCropW" />
      <input type="hidden" name="Croph" id="imageEditorCropH" />
    </form>

    <div class="info-bar">
      <div class="column titles">
        <div class="row current">
          <span class="uploaded-title">Uploaded image</span>
            <span class="cropped-title">Cropped image</span>
          </div>
        <div class="row recommended">Recommended image:</div>
      </div>

      <div class="column numbers">
        <div id="current-width" class="row current"></div>
        <div id="recommended-width" class="row recommended"></div>
      </div>

      <div class="column">
        <div class="row current">&times;</div>
        <div class="row recommended">&times;</div>
      </div>

      <div class="column numbers">
        <div id="current-height" class="row current"></div>
        <div id="recommended-height" class="row recommended"></div>
      </div>

      <div class="column left-text-position">
        <div class="row current">px at</div>
        <div class="row recommended">px at</div>
      </div>

      <div class="column numbers">
        <div id="current-dpi" class="row current"></div>
        <div id="recommended-dpi" class="row recommended"></div>
      </div>

      <div class="column">
        <div class="row current">dpi</div>
        <div class="row recommended">dpi</div>
      </div>

      <div class="column notice-switchers">
        <div class="row current outer">
          <div class="middle">
            <div class="icon question-sign inner" rel="current"></div>
          </div>
        </div>
        <div class="row recommended outer">
          <div class="middle">
            <div class="icon question-sign inner" rel="recommended" title="Required size for user uploaded image."></div>
          </div>
        </div>
      </div>

      <div class="column left-text-position last notices">
        <span class="default-notice">Move and resize the image and the frame to get the best fit.</span>
        <span class="low-resolution-notice">Drag the frame nodes to select a larger area or upload a larger image.</span>
      </div>

      <div class="reset"></div>
    </div>

    <div class="zetaprints-buttons-row">
      <div class="row-part first">
        <div id="restore-button" class="zetaprints-button restore-action">
          <div class="icon"></div>
          <span><?php echo $this->__('Reset'); ?></span>
        </div>
      </div>

      <div class="row-part">
        <div id="save-button" class="zetaprints-button save-action">
          <div class="icon"></div>
          <span><?php echo $this->__('Save'); ?></span>
        </div>

        <div class="reset"></div>
      </div>

      <div class="reset"></div>
    </div>
  </div>

</body>
</html>
