<meta http-equiv="Content-Type" content="<?php echo $this->getContentType() ?>" />

<script type="text/javascript">
//<![CDATA[
  var imageEditorUpdateURL = '<?php echo Mage::helper('webtoprint')
    ->_getUrl('web-to-print/image/update'); ?>';
  var imageEditorId = '<?php echo $this->getRequest()->getParam('id') ?>';
  var editor_image_url_template = '<?php echo Mage::helper('webtoprint')
    ->get_photo_thumbnail_url('image-guid.image-ext'); ?>';
  var imageEditorDelimeter = '&';
  var imageEditorQueryAppend = '';
//]]>
</script>

<script type="text/javascript" src="<?php echo Mage::getUrl('web-to-print/Trans'); ?>"></script>
<?php echo $this->getCssJsHtml() ?>
