<?php
  try {
    //Trying to load helper from web-to-print extension
    //We need to show real previews for web-to-print item
    $helper = $this->helper('webtoprint/personalization-form');
  } catch (Exception $e) {
    $helper = null;
  }
?>

<!-- Show web-to-print previews only then web-to-print extension is installed
     and product has web-to-print features -->
<?php if(!($helper && $helper->get_cart_image($this))): ?>
  <img src="<?php echo $this->getImageUrl(); ?>" width="75" height="75" alt="<?php echo $this->htmlEscape($this->getAltText()); ?>" />
<?php endif; ?>
