<div class="block">
    <a style="background-image: url('<?php echo $this->getSkinUrl('images/media/download-webtoprint-extension.png') ?>'); width: 195px; height: 85px; display: block;" href="http://www.magentocommerce.com/extension/1586" title="Download the latest version" />
  </a>
</div>

<div class="block">
  <div class="block-title">
    <strong><span>W2P resources</span></strong>
  </div>

  <div class="block-content">
    <p class="empty">
      <a href="http://www.zetaprints.com" title="Image generator" style="display:block;">ZP image generator</a>
      <a href="http://www.zetaprints.com/help" title="Web-to-print help" style="display:block;">Web-to-print help</a>
      <a href="http://www.zetaprints.com/help/category/magento" title="Extension installation and configuration" style="display:block;">Configuration help</a>
      <a href="http://www.zetaprints.com/help/category/design-techniques" title="Cool web-to-print designs" style="display:block;">Design examples</a>
      <a href="http://code.google.com/p/magento-w2p/source/checkout" title="Extension is open source" style="display:block;">Source code</a>
      <a href="http://code.google.com/p/magento-w2p/w/list" title="Help for developers" style="display:block;">Developer support</a>
    </p>
  </div>
</div>
